// File generated by Antigravity for Video Origin Analyzer
// Developer: Mahad and Mehdi Developers
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPp13ygXzwg00cArPVOZvqZ1Y-m0AFwsA',
    appId: '1:612351187132:web:8ab145dab127f5eba918b9',
    messagingSenderId: '612351187132',
    projectId: 'alteredtools',
    authDomain: 'alteredtools.firebaseapp.com',
    storageBucket: 'alteredtools.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPp13ygXzwg00cArPVOZvqZ1Y-m0AFwsA',
    appId: '1:612351187132:android:8ab145dab127f5eba918b9',
    messagingSenderId: '612351187132',
    projectId: 'alteredtools',
    storageBucket: 'alteredtools.firebasestorage.app',
    // Web client ID from google-services.json (client_type: 3) for Google Sign-In
    androidClientId: '612351187132-q3fjlnn2n7n8diskgr3orcqmedl7fnh7.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPp13ygXzwg00cArPVOZvqZ1Y-m0AFwsA',
    appId: '1:612351187132:ios:8ab145dab127f5eba918b9',
    messagingSenderId: '612351187132',
    projectId: 'alteredtools',
    storageBucket: 'alteredtools.firebasestorage.app',
    iosBundleId: 'com.mahadandmehdi.video_origin_analyzer',
  );
}

/// Google Sign-In Web Client ID (used by GoogleSignIn plugin for OAuth)
const String kGoogleSignInWebClientId =
    '612351187132-r3qrnh8660gcuuoik3p0ro14b7adi8k2.apps.googleusercontent.com';
